function out = login(cmd)
if nargin == 0
    cmd = 'init';
end
switch cmd
case 'init'
    fig = figure('Position',[245 380 200 120],...
            'Color',[0.7 0.7 0.7],...
            'NumberTitle','off',...
            'Resize','off',...
            'WindowStyle','modal',...
            'KeyPressFcn',[mfilename,' key']);
    uicontrol('Style','text',...
            'Position',[20 80 160 20],...
            'BackgroundColor',[0.7 0.7 0.7],...
            'FontSize',12,...
            'String','Enter User ID:',...
            'HorizontalAlignment','left');
    info.disp(1) = uicontrol('Style','edit',...
            'Position',[20 60 160 20],...
            'BackgroundColor','w',...
            'Enable','inactive',...
            'FontSize',10,...
            'HorizontalAlignment','left');
    uicontrol('Style','text',...
            'Position',[20 40 160 20],...
            'BackgroundColor',[0.7 0.7 0.7],...
            'FontSize',12,...
            'String','Enter Password:',...
            'HorizontalAlignment','left');
    info.disp(2) = uicontrol('Style','edit',...
            'Position',[20 20 160 20],...
            'BackgroundColor',[0.7 0.7 0.7],...
            'Enable','inactive',...
            'FontSize',10,...
            'HorizontalAlignment','left');
    info.str = {'',''};
    info.secret = [0 1];
    info.current = 1;
    if strncmpi(computer,'mac',3)
        info.bullet = '?';
    else
        info.bullet = '*';
    end
    set(fig,'UserData',info,...
            'HandleVisibility','callback')
    uiwait(fig)
    info = get(fig,'UserData');
    out = info.str;
    delete(fig)
case 'key'
    fig = gcbf;
    info = get(fig,'UserData');
    key = get(fig,'CurrentCharacter');
    switch double(key)
    case 9 % tab
        set(info.disp(info.current),'BackgroundColor',[0.7 0.7 0.7])
        info.current = rem(info.current,2) + 1;
        set(info.disp(info.current),'BackgroundColor','w')
    case 8 % delete
        if ~isempty(info.str{info.current})
            info.str{info.current}(end) = [];
        end
        if info.secret(info.current)
            set(info.disp(info.current),'String',...
                    repmat(info.bullet,1,length(info.str{info.current})))
        else
            set(info.disp(info.current),'String',info.str{info.current})
        end
    case {3,13} % return or enter (Macintosh)
        uiresume(fig)
    otherwise
        info.str{info.current} = [info.str{info.current},key];
        if info.secret(info.current)
            set(info.disp(info.current),'String',...
                    repmat(info.bullet,1,length(info.str{info.current})))
        else
            set(info.disp(info.current),'String',info.str{info.current})
        end
    end
    set(fig,'UserData',info)
end